config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
  #
  devise_for :users
  get "users/:id/profile", to: "users#profile_show", as: :user_profile
  get "users/:id/profile", to: "users#profile_edit", as: :edit_user_profile
  patch "users/:id/profile", to: "users#profile_update", as: :update_user_profile

  #
  # Pages
  get "about", to: "pages#about"
  # Products
  resources :products do
    # This adds product_remove_image path
    member do
      get "remove_image/:attachment_id", to: "products#remove_image", as: :remove_image
    end
  end
  # Route for webhook from Stripe
  post "/webhooks/stripe", to: "webhooks#set_stripe_webhook"
  #
  # Product Categories
  resources :product_categories do
    member do
      get :add_child
    end
  end

  resources :orders
  resources :cart_items, only: %i[ show create update ]
  # Note singular here since there will only ever be one cart per user session
  resource :cart, only: %i[ show edit update destroy ] do
    # Create checkout_cart_path, which maps to carts_controller checkout method
    post :checkout, on: :member
  end

  resources :reviews

  resources :review_notifications, only: %i[ index show update destroy ]

  # Search
  get "search", to: "search#index"
  get "clear", to: "search#clear"

  # for gem mission_control-jobs
  mount MissionControl::Jobs::Engine, at: "/jobs"

  # Catch-all for routing errors that excludes rails/active_storage.  Must be last route.  Directs to errors_controller routing_error method
  match "*unmatched_route",
      to: "errors#not_found",
      via: :all,
      constraints: ->(req) { !req.path.start_with?("/rails/active_storage") }
end

app/views/shared/_cart_drawer.html.erb
<div id="cart-drawer"
     data-controller="cart-drawer"
     class="fixed inset-y-0 right-0 z-50 flex flex-col w-full transition-transform duration-500 ease-in-out transform translate-x-full bg-white border shadow-md sm:w-2/3 md:w-1/2 lg:w-2/5 border-slate-500">

  <!-- Header with close button -->
  <div class="flex items-center justify-between p-4 border-b border-gray-200 bg-gray-50">
    <h2 class="text-lg font-semibold text-gray-800">Your Cart</h2>
    <button 
      type="button"
      data-action="click->cart-drawer#hide"
      class="text-gray-500 hover:text-gray-800">
      <%= render_icon("cancel", classes: "w-4 h-4 text-sm hover:cursor-pointer hover:scale-110") %>
    </button>
  </div>
  
  <!-- Cart contents -->
  <div class="flex-1 p-4 overflow-y-auto">
    <%= render partial: "carts/cart_table", locals: { cart: cart, cart_items: cart_items, editable: false } %>
  </div>
</div>

app/views/shared/_category_context_menu.html.erb
<div data-context-menu-target="menu"
     class="z-50 hidden w-24 border rounded shadow-md bg-indigo-50">

  <ul class="divide-y divide-gray-400">
    <li>
      <%= link_to "Add Child", add_child_product_category_path(record), 
                  class: "my-2 px-2 py-1 text-xs font-normal hover:bg-blue-200 hover:rounded-md" %>
    </li>
    <li>
      <%= link_to "Add Product", new_product_path(product_category_id: record.id), 
                  class: "my-2 px-2 py-1 text-xs font-normal hover:bg-blue-200 hover:rounded-md" %>
    </li>
    <li>
      <%= link_to "Edit", edit_product_category_path(record), 
                  class: "my-2 pl-2 pr-6 py-1 text-xs font-normal hover:bg-blue-200 hover:rounded-md" %>
    </li>
  </ul>
  
</div>

app/views/shared/_error_msgs.html.erb
<% if obj.errors.any? %>
  <div class="px-4 py-2 my-2 bg-yellow-200 border border-red-400 rounded-md shadow-md w-fit">
    <h3 class="mb-2 font-semibold text-red-700">
      <%= pluralize(obj.errors.count, "error") %> prohibited this 
      <%= obj.class.name.downcase %> from being saved:
    </h3>

    <ol class="space-y-1 text-red-600 list-decimal list-inside">
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>

  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |msg_type, message| %>
    <%# data-controller:  identifies teh stimulus controller involved %>
    <%# data-dismiss-target:  identifies the dom_id of whatever is to be dismissed %>
    <div data-controller ="dismiss" 
        data-dismiss-target="dismissthis" 
        class="flex w-fit align-middle px-4 border rounded-md border-slate-700 shadow-md mb-1 relative 
                <%= flash_message_display_class(msg_type) %>">

      <div id="dismiss-this">
        <b><%="#{Rails.configuration.application_name}: "%></b> <%=message%>
      </div>
    
      <button data-action="click->dismiss#close" 
              class="ml-2 transition ease-in-out cursor-pointer hover:-translate-y-1 hover:scale-110">
        &#x1F5D1;
      </button>

    </div>
  <% end %>
</div>

app/views/shared/_user_profileimage.html.erb
<% if user.profile_image.attached? %>
  <!-- Image configured by user -->
  <%= image_tag user.profile_image, class: "inline-block h-8 w-8 rounded-full", alt: user.name %>
<% else %>
  <!-- "Person" icon" -->
  <%= render_icon("person", classes: "mr-2 size-6") %>
<% end %>